{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Para executar os testes, basta executar o comando abaixo:\n",
    "\n",
    "```bash\n",
    "python -m pytest\n",
    "```\n",
    "\n",
    "Alternativamente, rode a celula abaixo"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1055,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pymongo in c:\\users\\rodrigopintucci\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\\localcache\\local-packages\\python39\\site-packages (from -r requirements.txt (line 1)) (4.6.1)\n",
      "Requirement already satisfied: customtkinter in c:\\users\\rodrigopintucci\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\\localcache\\local-packages\\python39\\site-packages (from -r requirements.txt (line 2)) (5.2.1)\n",
      "Requirement already satisfied: pytest in c:\\users\\rodrigopintucci\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\\localcache\\local-packages\\python39\\site-packages (from -r requirements.txt (line 3)) (7.4.3)\n",
      "Requirement already satisfied: bcrypt in c:\\users\\rodrigopintucci\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\\localcache\\local-packages\\python39\\site-packages (from -r requirements.txt (line 4)) (4.1.1)\n",
      "Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in c:\\users\\rodrigopintucci\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\\localcache\\local-packages\\python39\\site-packages (from pymongo->-r requirements.txt (line 1)) (2.4.2)\n",
      "Requirement already satisfied: darkdetect in c:\\users\\rodrigopintucci\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\\localcache\\local-packages\\python39\\site-packages (from customtkinter->-r requirements.txt (line 2)) (0.8.0)\n",
      "Requirement already satisfied: exceptiongroup>=1.0.0rc8 in c:\\users\\rodrigopintucci\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\\localcache\\local-packages\\python39\\site-packages (from pytest->-r requirements.txt (line 3)) (1.2.0)\n",
      "Requirement already satisfied: pluggy<2.0,>=0.12 in c:\\users\\rodrigopintucci\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\\localcache\\local-packages\\python39\\site-packages (from pytest->-r requirements.txt (line 3)) (1.3.0)\n",
      "Requirement already satisfied: tomli>=1.0.0 in c:\\users\\rodrigopintucci\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\\localcache\\local-packages\\python39\\site-packages (from pytest->-r requirements.txt (line 3)) (2.0.1)\n",
      "Requirement already satisfied: colorama in c:\\users\\rodrigopintucci\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\\localcache\\local-packages\\python39\\site-packages (from pytest->-r requirements.txt (line 3)) (0.3.9)\n",
      "Requirement already satisfied: iniconfig in c:\\users\\rodrigopintucci\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\\localcache\\local-packages\\python39\\site-packages (from pytest->-r requirements.txt (line 3)) (2.0.0)\n",
      "Requirement already satisfied: packaging in c:\\users\\rodrigopintucci\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\\localcache\\local-packages\\python39\\site-packages (from pytest->-r requirements.txt (line 3)) (21.3)\n",
      "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\\users\\rodrigopintucci\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\\localcache\\local-packages\\python39\\site-packages (from packaging->pytest->-r requirements.txt (line 3)) (3.0.9)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "[notice] A new release of pip available: 22.3.1 -> 23.3.1\n",
      "[notice] To update, run: C:\\Users\\RodrigoPintucci\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\python.exe -m pip install --upgrade pip\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "============================= test session starts =============================\n",
      "platform win32 -- Python 3.9.13, pytest-7.4.3, pluggy-1.3.0\n",
      "rootdir: c:\\Users\\RodrigoPintucci\\Documents\\EngenhariaSoftware\\Engenharia_Software\n",
      "collected 213 items\n",
      "\n",
      "tests\\test_auth\\test_authentication_module.py .....                      [  2%]\n",
      "tests\\test_events\\test_element_event.py ...FFFF.....................     [ 15%]\n",
      "tests\\test_events\\test_element_factory.py ....                           [ 17%]\n",
      "tests\\test_events\\test_element_management.py ...................         [ 26%]\n",
      "tests\\test_events\\test_element_reminder.py ..........................    [ 38%]\n",
      "tests\\test_events\\test_element_task.py .............................     [ 52%]\n",
      "tests\\test_mongomodule\\test_mongo_module.py ......                       [ 54%]\n",
      "tests\\test_schedule\\test_schedule_management.py ........................ [ 66%]\n",
      ".....                                                                    [ 68%]\n",
      "tests\\test_schedule\\test_schedule_model.py ............................. [ 82%]\n",
      "                                                                         [ 82%]\n",
      "tests\\test_schedule\\test_schedule_observer.py .......                    [ 85%]\n",
      "tests\\test_users\\test_user_management_module.py .FFFF.......             [ 91%]\n",
      "tests\\test_users\\test_user_model.py ...................                  [100%]\n",
      "\n",
      "================================== FAILURES ===================================\n",
      "_______________________ TestEventElement.test_get_users _______________________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_events.test_element_event.TestEventElement testMethod=test_get_users>\n",
      "\n",
      "    def test_get_users(self):\n",
      "        \"\"\"\n",
      "        Test if the users returned match the ones that were set in the\n",
      "        constructor\n",
      "        \"\"\"\n",
      "        # Set up the mock objects and functions\n",
      "        get_schedule_mock, _, _ = self.get_mock_schedule()\n",
      "        get_user_mock, user_1, user_2, user_3, user_4 = self.get_mock_user()\n",
      "    \n",
      "        with unittest.mock.patch.object(\n",
      "            ScheduleManagement, \"get_schedule\", side_effect=get_schedule_mock\n",
      "        ):\n",
      "            with unittest.mock.patch.object(\n",
      "                UserManagement, \"get_user\", side_effect=get_user_mock\n",
      "            ):\n",
      "                users = self.event.get_users([\"schedule_1\", \"schedule_2\"])\n",
      "                self.assertEqual(len(users), 4)\n",
      "                for user in users:\n",
      ">                   self.assertIn(user, [user_1, user_2, user_3, user_4])\n",
      "E                   AssertionError: <MagicMock id='2910893071232'> not found in [<MagicMock spec='User' id='2910893306304'>, <MagicMock spec='User' id='2910893326096'>, <MagicMock spec='User' id='2910893306256'>, <MagicMock spec='User' id='2910893281776'>]\n",
      "\n",
      "tests\\test_events\\test_element_event.py:94: AssertionError\n",
      "__________________ TestEventElement.test_get_users_nonfilter __________________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_events.test_element_event.TestEventElement testMethod=test_get_users_nonfilter>\n",
      "\n",
      "    def test_get_users_nonfilter(self):\n",
      "        \"\"\"Test get_users when no filter of schedules are not specified.\n",
      "        Default to all schedules.\n",
      "        #\"\"\"\n",
      "        # Set up the mock objects and functions\n",
      "        get_schedule_mock, _, _ = self.get_mock_schedule()\n",
      "        get_user_mock, user_1, user_2, user_3, user_4 = self.get_mock_user()\n",
      "    \n",
      "        with unittest.mock.patch.object(\n",
      "            ScheduleManagement, \"get_schedule\", side_effect=get_schedule_mock\n",
      "        ):\n",
      "            with unittest.mock.patch.object(\n",
      "                UserManagement, \"get_user\", side_effect=get_user_mock\n",
      "            ):\n",
      "                users = self.event.get_users()\n",
      "                self.assertEqual(len(users), 4)\n",
      "                for user in users:\n",
      ">                   self.assertIn(user, [user_1, user_2, user_3, user_4])\n",
      "E                   AssertionError: <MagicMock id='2910893071232'> not found in [<MagicMock spec='User' id='2910893438864'>, <MagicMock spec='User' id='2910893331264'>, <MagicMock spec='User' id='2910893274640'>, <MagicMock spec='User' id='2910893330832'>]\n",
      "\n",
      "tests\\test_events\\test_element_event.py:113: AssertionError\n",
      "_______________ TestEventElement.test_get_users_nonrepeat_users _______________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_events.test_element_event.TestEventElement testMethod=test_get_users_nonrepeat_users>\n",
      "\n",
      "    def test_get_users_nonrepeat_users(self):\n",
      "        \"\"\"Test if the users returned are unique\"\"\"\n",
      "        # Set up the mock objects\n",
      "        get_schedule_mock, _, _ = self.get_mock_schedule(\n",
      "            repeat_user=True\n",
      "        )\n",
      "        get_user_mock, user_1, user_2, _, _ = self.get_mock_user()\n",
      "    \n",
      "        with unittest.mock.patch.object(\n",
      "            ScheduleManagement, \"get_schedule\", side_effect=get_schedule_mock\n",
      "        ):\n",
      "            with unittest.mock.patch.object(\n",
      "                UserManagement, \"get_user\", side_effect=get_user_mock\n",
      "            ):\n",
      "                users = self.event.get_users([\"schedule_1\", \"schedule_2\"])\n",
      "                self.assertEqual(len(users), 2)\n",
      "                for user in users:\n",
      ">                   self.assertIn(user, [user_1, user_2])\n",
      "E                   AssertionError: <MagicMock id='2910893071232'> not found in [<MagicMock spec='User' id='2910894184576'>, <MagicMock spec='User' id='2910894288752'>]\n",
      "\n",
      "tests\\test_events\\test_element_event.py:152: AssertionError\n",
      "__________ TestEventElement.test_get_users_with_filter_by_schedules ___________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_events.test_element_event.TestEventElement testMethod=test_get_users_with_filter_by_schedules>\n",
      "\n",
      "    def test_get_users_with_filter_by_schedules(self):\n",
      "        \"\"\"\n",
      "        Test if the users returned match the ones that were set in the\n",
      "        constructor and if they belong to the specified schedules\n",
      "        \"\"\"\n",
      "        # Set up the mock objects\n",
      "        get_schedule_mock, _, _ = self.get_mock_schedule()\n",
      "        get_user_mock, user_1, user_2, user_3, user_4 = self.get_mock_user()\n",
      "    \n",
      "        with unittest.mock.patch.object(\n",
      "            ScheduleManagement, \"get_schedule\", side_effect=get_schedule_mock\n",
      "        ):\n",
      "            with unittest.mock.patch.object(\n",
      "                UserManagement, \"get_user\", side_effect=get_user_mock\n",
      "            ):\n",
      "                users = self.event.get_users([\"schedule_1\"])\n",
      "                self.assertEqual(len(users), 2)\n",
      "                for user in users:\n",
      ">                   self.assertIn(user, [user_1, user_2, user_3, user_4])\n",
      "E                   AssertionError: <MagicMock id='2910893071232'> not found in [<MagicMock spec='User' id='2910894410000'>, <MagicMock spec='User' id='2910893325520'>, <MagicMock spec='User' id='2910894409856'>, <MagicMock spec='User' id='2910893323648'>]\n",
      "\n",
      "tests\\test_events\\test_element_event.py:133: AssertionError\n",
      "_____________ TestUserManagementModule.test_add_schedule_to_user ______________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_users.test_user_management_module.TestUserManagementModule testMethod=test_add_schedule_to_user>\n",
      "\n",
      "    def test_add_schedule_to_user(self):\n",
      "        \"\"\"Test adding a schedule to a user\"\"\"\n",
      "        self.db_module.select_data = MagicMock(return_value = ['a'])\n",
      "        self.db_module.update_data = MagicMock()\n",
      "        self.user_management.user_exists = MagicMock(return_value=True)\n",
      "        self.user_management.users = {\"test_id\": User(\"test_id\", \"test_user\",\n",
      "                                                        \"test_email\", [],\n",
      "                                                        \"test_password\")}\n",
      ">       self.user_management.add_schedule_to_user(\"test_id\", \"test_schedule\",\n",
      "                                                  \"write\")\n",
      "\n",
      "tests\\test_users\\test_user_management_module.py:192: \n",
      "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n",
      "src\\user\\user_management.py:208: in add_schedule_to_user\n",
      "    user = self.get_user(user_id)\n",
      "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n",
      "\n",
      "self = <src.user.user_management.UserManagement object at 0x000002A5BECDFA00>\n",
      "user_id = 'test_id'\n",
      "\n",
      "    def get_user(self, user_id: str) -> User:\n",
      "        \"\"\"\n",
      "        Get a user\n",
      "    \n",
      "        Args:\n",
      "            user_id: User ID\n",
      "    \n",
      "        Returns:\n",
      "            The user if it exists, None otherwise\n",
      "        \"\"\"\n",
      "        data = self.db_module.select_data('users', {\"_id\": user_id})\n",
      ">       print(data[0])\n",
      "E       TypeError: 'Mock' object is not subscriptable\n",
      "\n",
      "src\\user\\user_management.py:164: TypeError\n",
      "_____________ TestUserManagementModule.test_create_blank_username _____________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_users.test_user_management_module.TestUserManagementModule testMethod=test_create_blank_username>\n",
      "\n",
      "    def test_create_blank_username(self):\n",
      "        \"\"\"Test creating a user with a blank username\"\"\"\n",
      "        with self.assertRaises(UsernameCantBeBlank) as context:\n",
      ">           self.user_management.create_user(username=\"\",\n",
      "                            email=\"test_email\", password=\"test_password\", id=\"1\")\n",
      "E           TypeError: create_user() got an unexpected keyword argument 'id'\n",
      "\n",
      "tests\\test_users\\test_user_management_module.py:85: TypeError\n",
      "_____________ TestUserManagementModule.test_create_existing_user ______________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_users.test_user_management_module.TestUserManagementModule testMethod=test_create_existing_user>\n",
      "\n",
      "    def test_create_existing_user(self):\n",
      "        \"\"\"Test creating a user that already exists\"\"\"\n",
      "        self.db_module.select_data = MagicMock(return_value =\n",
      "                                    [{\"username\": \"test_user\",\n",
      "                                      \"email\": \"test_email\",\n",
      "                                      \"hashed_password\": \"test_hashed_password\"}])\n",
      "    \n",
      "        with self.assertRaises(DuplicatedIDError) as context:\n",
      ">           self.user_management.create_user(username=\"test_user\",\n",
      "                            email=\"test_email\", password=\"test_password\", id=\"1\")\n",
      "E           TypeError: create_user() got an unexpected keyword argument 'id'\n",
      "\n",
      "tests\\test_users\\test_user_management_module.py:77: TypeError\n",
      "______________ TestUserManagementModule.test_create_user_success ______________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_users.test_user_management_module.TestUserManagementModule testMethod=test_create_user_success>\n",
      "\n",
      "    def test_create_user_success(self):\n",
      "        \"\"\"Test creating a new user successfully\"\"\"\n",
      "        self.db_module.insert_data = MagicMock(return_value =\n",
      "                                    [{\"username\": \"test_user\",\n",
      "                                      \"email\": \"test_email\",\n",
      "                                      \"hashed_password\": \"test_hashed_password\"}])\n",
      "        self.db_module.select_data = MagicMock(return_value = [])\n",
      ">       result = self.user_management.create_user(username=\"test_user\",\n",
      "                        email=\"test_email\", password=\"test_password\", user_id=\"1\")\n",
      "\n",
      "tests\\test_users\\test_user_management_module.py:39: \n",
      "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n",
      "src\\user\\user_management.py:78: in create_user\n",
      "    if self.user_exists(user_id):\n",
      "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n",
      "\n",
      "self = <src.user.user_management.UserManagement object at 0x000002A5BEC4ADF0>\n",
      "user_id = '1'\n",
      "\n",
      "    def user_exists(self, user_id: str) -> bool:\n",
      "        \"\"\"\n",
      "        Check if a user exists\n",
      "    \n",
      "        Args:\n",
      "            user_id: User ID\n",
      "    \n",
      "        Returns:\n",
      "            True if the user exists, False otherwise\n",
      "        \"\"\"\n",
      "        data = self.db_module.select_data('users', {\"_id\": user_id})\n",
      ">       return len(data) > 0\n",
      "E       TypeError: object of type 'Mock' has no len()\n",
      "\n",
      "src\\user\\user_management.py:137: TypeError\n",
      "=========================== short test summary info ===========================\n",
      "FAILED tests/test_events/test_element_event.py::TestEventElement::test_get_users\n",
      "FAILED tests/test_events/test_element_event.py::TestEventElement::test_get_users_nonfilter\n",
      "FAILED tests/test_events/test_element_event.py::TestEventElement::test_get_users_nonrepeat_users\n",
      "FAILED tests/test_events/test_element_event.py::TestEventElement::test_get_users_with_filter_by_schedules\n",
      "FAILED tests/test_users/test_user_management_module.py::TestUserManagementModule::test_add_schedule_to_user\n",
      "FAILED tests/test_users/test_user_management_module.py::TestUserManagementModule::test_create_blank_username\n",
      "FAILED tests/test_users/test_user_management_module.py::TestUserManagementModule::test_create_existing_user\n",
      "FAILED tests/test_users/test_user_management_module.py::TestUserManagementModule::test_create_user_success\n",
      "======================== 8 failed, 205 passed in 1.21s ========================\n"
     ]
    }
   ],
   "source": [
    "!pip install -r requirements.txt\n",
    "!python -m pytest"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1056,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: coverage in c:\\users\\rodrigopintucci\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\\localcache\\local-packages\\python39\\site-packages (7.3.2)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "[notice] A new release of pip available: 22.3.1 -> 23.3.1\n",
      "[notice] To update, run: C:\\Users\\RodrigoPintucci\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\python.exe -m pip install --upgrade pip\n"
     ]
    }
   ],
   "source": [
    "!pip install coverage"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1057,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "============================= test session starts =============================\n",
      "platform win32 -- Python 3.9.13, pytest-7.4.3, pluggy-1.3.0\n",
      "rootdir: c:\\Users\\RodrigoPintucci\\Documents\\EngenhariaSoftware\\Engenharia_Software\n",
      "collected 213 items\n",
      "\n",
      "tests\\test_auth\\test_authentication_module.py .....                      [  2%]\n",
      "tests\\test_events\\test_element_event.py ...FFFF.....................     [ 15%]\n",
      "tests\\test_events\\test_element_factory.py ....                           [ 17%]\n",
      "tests\\test_events\\test_element_management.py ...................         [ 26%]\n",
      "tests\\test_events\\test_element_reminder.py ..........................    [ 38%]\n",
      "tests\\test_events\\test_element_task.py .............................     [ 52%]\n",
      "tests\\test_mongomodule\\test_mongo_module.py ......                       [ 54%]\n",
      "tests\\test_schedule\\test_schedule_management.py ........................ [ 66%]\n",
      ".....                                                                    [ 68%]\n",
      "tests\\test_schedule\\test_schedule_model.py ............................. [ 82%]\n",
      "                                                                         [ 82%]\n",
      "tests\\test_schedule\\test_schedule_observer.py .......                    [ 85%]\n",
      "tests\\test_users\\test_user_management_module.py .FFFF.......             [ 91%]\n",
      "tests\\test_users\\test_user_model.py ...................                  [100%]\n",
      "\n",
      "================================== FAILURES ===================================\n",
      "_______________________ TestEventElement.test_get_users _______________________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_events.test_element_event.TestEventElement testMethod=test_get_users>\n",
      "\n",
      "    def test_get_users(self):\n",
      "        \"\"\"\n",
      "        Test if the users returned match the ones that were set in the\n",
      "        constructor\n",
      "        \"\"\"\n",
      "        # Set up the mock objects and functions\n",
      "        get_schedule_mock, _, _ = self.get_mock_schedule()\n",
      "        get_user_mock, user_1, user_2, user_3, user_4 = self.get_mock_user()\n",
      "    \n",
      "        with unittest.mock.patch.object(\n",
      "            ScheduleManagement, \"get_schedule\", side_effect=get_schedule_mock\n",
      "        ):\n",
      "            with unittest.mock.patch.object(\n",
      "                UserManagement, \"get_user\", side_effect=get_user_mock\n",
      "            ):\n",
      "                users = self.event.get_users([\"schedule_1\", \"schedule_2\"])\n",
      "                self.assertEqual(len(users), 4)\n",
      "                for user in users:\n",
      ">                   self.assertIn(user, [user_1, user_2, user_3, user_4])\n",
      "E                   AssertionError: <MagicMock id='2208649501712'> not found in [<MagicMock spec='User' id='2208649780816'>, <MagicMock spec='User' id='2208649826704'>, <MagicMock spec='User' id='2208649780912'>, <MagicMock spec='User' id='2208649826656'>]\n",
      "\n",
      "tests\\test_events\\test_element_event.py:94: AssertionError\n",
      "__________________ TestEventElement.test_get_users_nonfilter __________________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_events.test_element_event.TestEventElement testMethod=test_get_users_nonfilter>\n",
      "\n",
      "    def test_get_users_nonfilter(self):\n",
      "        \"\"\"Test get_users when no filter of schedules are not specified.\n",
      "        Default to all schedules.\n",
      "        #\"\"\"\n",
      "        # Set up the mock objects and functions\n",
      "        get_schedule_mock, _, _ = self.get_mock_schedule()\n",
      "        get_user_mock, user_1, user_2, user_3, user_4 = self.get_mock_user()\n",
      "    \n",
      "        with unittest.mock.patch.object(\n",
      "            ScheduleManagement, \"get_schedule\", side_effect=get_schedule_mock\n",
      "        ):\n",
      "            with unittest.mock.patch.object(\n",
      "                UserManagement, \"get_user\", side_effect=get_user_mock\n",
      "            ):\n",
      "                users = self.event.get_users()\n",
      "                self.assertEqual(len(users), 4)\n",
      "                for user in users:\n",
      ">                   self.assertIn(user, [user_1, user_2, user_3, user_4])\n",
      "E                   AssertionError: <MagicMock id='2208649501712'> not found in [<MagicMock spec='User' id='2208649789056'>, <MagicMock spec='User' id='2208649857152'>, <MagicMock spec='User' id='2208649789152'>, <MagicMock spec='User' id='2208649767184'>]\n",
      "\n",
      "tests\\test_events\\test_element_event.py:113: AssertionError\n",
      "_______________ TestEventElement.test_get_users_nonrepeat_users _______________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_events.test_element_event.TestEventElement testMethod=test_get_users_nonrepeat_users>\n",
      "\n",
      "    def test_get_users_nonrepeat_users(self):\n",
      "        \"\"\"Test if the users returned are unique\"\"\"\n",
      "        # Set up the mock objects\n",
      "        get_schedule_mock, _, _ = self.get_mock_schedule(\n",
      "            repeat_user=True\n",
      "        )\n",
      "        get_user_mock, user_1, user_2, _, _ = self.get_mock_user()\n",
      "    \n",
      "        with unittest.mock.patch.object(\n",
      "            ScheduleManagement, \"get_schedule\", side_effect=get_schedule_mock\n",
      "        ):\n",
      "            with unittest.mock.patch.object(\n",
      "                UserManagement, \"get_user\", side_effect=get_user_mock\n",
      "            ):\n",
      "                users = self.event.get_users([\"schedule_1\", \"schedule_2\"])\n",
      "                self.assertEqual(len(users), 2)\n",
      "                for user in users:\n",
      ">                   self.assertIn(user, [user_1, user_2])\n",
      "E                   AssertionError: <MagicMock id='2208649501712'> not found in [<MagicMock spec='User' id='2208649460608'>, <MagicMock spec='User' id='2208649431792'>]\n",
      "\n",
      "tests\\test_events\\test_element_event.py:152: AssertionError\n",
      "__________ TestEventElement.test_get_users_with_filter_by_schedules ___________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_events.test_element_event.TestEventElement testMethod=test_get_users_with_filter_by_schedules>\n",
      "\n",
      "    def test_get_users_with_filter_by_schedules(self):\n",
      "        \"\"\"\n",
      "        Test if the users returned match the ones that were set in the\n",
      "        constructor and if they belong to the specified schedules\n",
      "        \"\"\"\n",
      "        # Set up the mock objects\n",
      "        get_schedule_mock, _, _ = self.get_mock_schedule()\n",
      "        get_user_mock, user_1, user_2, user_3, user_4 = self.get_mock_user()\n",
      "    \n",
      "        with unittest.mock.patch.object(\n",
      "            ScheduleManagement, \"get_schedule\", side_effect=get_schedule_mock\n",
      "        ):\n",
      "            with unittest.mock.patch.object(\n",
      "                UserManagement, \"get_user\", side_effect=get_user_mock\n",
      "            ):\n",
      "                users = self.event.get_users([\"schedule_1\"])\n",
      "                self.assertEqual(len(users), 2)\n",
      "                for user in users:\n",
      ">                   self.assertIn(user, [user_1, user_2, user_3, user_4])\n",
      "E                   AssertionError: <MagicMock id='2208649501712'> not found in [<MagicMock spec='User' id='2208649826944'>, <MagicMock spec='User' id='2208649777408'>, <MagicMock spec='User' id='2208649782560'>, <MagicMock spec='User' id='2208649777984'>]\n",
      "\n",
      "tests\\test_events\\test_element_event.py:133: AssertionError\n",
      "_____________ TestUserManagementModule.test_add_schedule_to_user ______________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_users.test_user_management_module.TestUserManagementModule testMethod=test_add_schedule_to_user>\n",
      "\n",
      "    def test_add_schedule_to_user(self):\n",
      "        \"\"\"Test adding a schedule to a user\"\"\"\n",
      "        self.db_module.select_data = MagicMock(return_value = ['a'])\n",
      "        self.db_module.update_data = MagicMock()\n",
      "        self.user_management.user_exists = MagicMock(return_value=True)\n",
      "        self.user_management.users = {\"test_id\": User(\"test_id\", \"test_user\",\n",
      "                                                        \"test_email\", [],\n",
      "                                                        \"test_password\")}\n",
      ">       self.user_management.add_schedule_to_user(\"test_id\", \"test_schedule\",\n",
      "                                                  \"write\")\n",
      "\n",
      "tests\\test_users\\test_user_management_module.py:192: \n",
      "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n",
      "src\\user\\user_management.py:208: in add_schedule_to_user\n",
      "    user = self.get_user(user_id)\n",
      "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n",
      "\n",
      "self = <src.user.user_management.UserManagement object at 0x000002023E0D2250>\n",
      "user_id = 'test_id'\n",
      "\n",
      "    def get_user(self, user_id: str) -> User:\n",
      "        \"\"\"\n",
      "        Get a user\n",
      "    \n",
      "        Args:\n",
      "            user_id: User ID\n",
      "    \n",
      "        Returns:\n",
      "            The user if it exists, None otherwise\n",
      "        \"\"\"\n",
      "        data = self.db_module.select_data('users', {\"_id\": user_id})\n",
      ">       print(data[0])\n",
      "E       TypeError: 'Mock' object is not subscriptable\n",
      "\n",
      "src\\user\\user_management.py:164: TypeError\n",
      "_____________ TestUserManagementModule.test_create_blank_username _____________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_users.test_user_management_module.TestUserManagementModule testMethod=test_create_blank_username>\n",
      "\n",
      "    def test_create_blank_username(self):\n",
      "        \"\"\"Test creating a user with a blank username\"\"\"\n",
      "        with self.assertRaises(UsernameCantBeBlank) as context:\n",
      ">           self.user_management.create_user(username=\"\",\n",
      "                            email=\"test_email\", password=\"test_password\", id=\"1\")\n",
      "E           TypeError: create_user() got an unexpected keyword argument 'id'\n",
      "\n",
      "tests\\test_users\\test_user_management_module.py:85: TypeError\n",
      "_____________ TestUserManagementModule.test_create_existing_user ______________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_users.test_user_management_module.TestUserManagementModule testMethod=test_create_existing_user>\n",
      "\n",
      "    def test_create_existing_user(self):\n",
      "        \"\"\"Test creating a user that already exists\"\"\"\n",
      "        self.db_module.select_data = MagicMock(return_value =\n",
      "                                    [{\"username\": \"test_user\",\n",
      "                                      \"email\": \"test_email\",\n",
      "                                      \"hashed_password\": \"test_hashed_password\"}])\n",
      "    \n",
      "        with self.assertRaises(DuplicatedIDError) as context:\n",
      ">           self.user_management.create_user(username=\"test_user\",\n",
      "                            email=\"test_email\", password=\"test_password\", id=\"1\")\n",
      "E           TypeError: create_user() got an unexpected keyword argument 'id'\n",
      "\n",
      "tests\\test_users\\test_user_management_module.py:77: TypeError\n",
      "______________ TestUserManagementModule.test_create_user_success ______________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_users.test_user_management_module.TestUserManagementModule testMethod=test_create_user_success>\n",
      "\n",
      "    def test_create_user_success(self):\n",
      "        \"\"\"Test creating a new user successfully\"\"\"\n",
      "        self.db_module.insert_data = MagicMock(return_value =\n",
      "                                    [{\"username\": \"test_user\",\n",
      "                                      \"email\": \"test_email\",\n",
      "                                      \"hashed_password\": \"test_hashed_password\"}])\n",
      "        self.db_module.select_data = MagicMock(return_value = [])\n",
      ">       result = self.user_management.create_user(username=\"test_user\",\n",
      "                        email=\"test_email\", password=\"test_password\", user_id=\"1\")\n",
      "\n",
      "tests\\test_users\\test_user_management_module.py:39: \n",
      "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n",
      "src\\user\\user_management.py:78: in create_user\n",
      "    if self.user_exists(user_id):\n",
      "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n",
      "\n",
      "self = <src.user.user_management.UserManagement object at 0x000002023E0E6B80>\n",
      "user_id = '1'\n",
      "\n",
      "    def user_exists(self, user_id: str) -> bool:\n",
      "        \"\"\"\n",
      "        Check if a user exists\n",
      "    \n",
      "        Args:\n",
      "            user_id: User ID\n",
      "    \n",
      "        Returns:\n",
      "            True if the user exists, False otherwise\n",
      "        \"\"\"\n",
      "        data = self.db_module.select_data('users', {\"_id\": user_id})\n",
      ">       return len(data) > 0\n",
      "E       TypeError: object of type 'Mock' has no len()\n",
      "\n",
      "src\\user\\user_management.py:137: TypeError\n",
      "=========================== short test summary info ===========================\n",
      "FAILED tests/test_events/test_element_event.py::TestEventElement::test_get_users\n",
      "FAILED tests/test_events/test_element_event.py::TestEventElement::test_get_users_nonfilter\n",
      "FAILED tests/test_events/test_element_event.py::TestEventElement::test_get_users_nonrepeat_users\n",
      "FAILED tests/test_events/test_element_event.py::TestEventElement::test_get_users_with_filter_by_schedules\n",
      "FAILED tests/test_users/test_user_management_module.py::TestUserManagementModule::test_add_schedule_to_user\n",
      "FAILED tests/test_users/test_user_management_module.py::TestUserManagementModule::test_create_blank_username\n",
      "FAILED tests/test_users/test_user_management_module.py::TestUserManagementModule::test_create_existing_user\n",
      "FAILED tests/test_users/test_user_management_module.py::TestUserManagementModule::test_create_user_success\n",
      "======================== 8 failed, 205 passed in 1.61s ========================\n"
     ]
    }
   ],
   "source": [
    "!coverage run -m pytest"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1058,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The autoreload extension is already loaded. To reload it, use:\n",
      "  %reload_ext autoreload\n"
     ]
    }
   ],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1059,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Name                                          Stmts   Miss  Cover\n",
      "-----------------------------------------------------------------\n",
      "src\\auth\\authentication.py                       22      2    91%\n",
      "src\\calendar_elements\\element_factory.py         12      0   100%\n",
      "src\\calendar_elements\\element_interface.py       24      1    96%\n",
      "src\\calendar_elements\\element_management.py      83      2    98%\n",
      "src\\calendar_elements\\element_types.py          231      7    97%\n",
      "src\\database\\database_module.py                  14      0   100%\n",
      "src\\database\\mongo_module.py                     44      0   100%\n",
      "src\\database\\utils.py                            65     50    23%\n",
      "src\\observer\\observer.py                         14      1    93%\n",
      "src\\schedule\\schedule_management.py              99      1    99%\n",
      "src\\schedule\\schedule_model.py                   79      4    95%\n",
      "src\\user\\user_management.py                      84     23    73%\n",
      "src\\user\\user_model.py                          107     19    82%\n",
      "-----------------------------------------------------------------\n",
      "TOTAL                                           878    110    87%\n"
     ]
    }
   ],
   "source": [
    "# explicação do copitot:\n",
    "# Name: nome do arquivo testado\n",
    "# Stmts: número de linhas executadas\n",
    "# Miss: número de linhas não executadas\n",
    "# Cover: porcentagem de cobertura\n",
    "# Missing: linhas não executadas\n",
    "# !coverage report -m\n",
    "\n",
    "!coverage report --omit \"*__init__*,*/lib/*,tests/*\""
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Rode a célula (ou o comando) abaixo para gerar um relatório de cobertura em html dos testes:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1060,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Wrote HTML report to htmlcov\\index.html\n"
     ]
    }
   ],
   "source": [
    "!coverage html --omit \"*__init__*,*/lib/*,tests/*\"\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1061,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "============================= test session starts =============================\n",
      "platform win32 -- Python 3.9.13, pytest-7.4.3, pluggy-1.3.0\n",
      "rootdir: c:\\Users\\RodrigoPintucci\\Documents\\EngenhariaSoftware\\Engenharia_Software\n",
      "collected 28 items\n",
      "\n",
      "tests\\test_events\\test_element_event.py ............................     [100%]\n",
      "\n",
      "============================= 28 passed in 0.43s ==============================\n"
     ]
    }
   ],
   "source": [
    "# rodando um teste específico\n",
    "!coverage run -m pytest tests/test_events/test_element_event.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1062,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "============================= test session starts =============================\n",
      "platform win32 -- Python 3.9.13, pytest-7.4.3, pluggy-1.3.0\n",
      "rootdir: c:\\Users\\RodrigoPintucci\\Documents\\EngenhariaSoftware\\Engenharia_Software\n",
      "collected 7 items\n",
      "\n",
      "tests\\test_schedule\\test_schedule_observer.py .......                    [100%]\n",
      "\n",
      "============================== 7 passed in 0.32s ==============================\n"
     ]
    }
   ],
   "source": [
    "# rodando um teste específico\n",
    "!coverage run -m pytest tests/test_schedule/test_schedule_observer.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1067,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "============================= test session starts =============================\n",
      "platform win32 -- Python 3.9.13, pytest-7.4.3, pluggy-1.3.0\n",
      "rootdir: c:\\Users\\RodrigoPintucci\\Documents\\EngenhariaSoftware\\Engenharia_Software\n",
      "collected 12 items\n",
      "\n",
      "tests\\test_users\\test_user_management_module.py .F..........             [100%]\n",
      "\n",
      "================================== FAILURES ===================================\n",
      "_____________ TestUserManagementModule.test_add_schedule_to_user ______________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_users.test_user_management_module.TestUserManagementModule testMethod=test_add_schedule_to_user>\n",
      "\n",
      "    def test_add_schedule_to_user(self):\n",
      "        \"\"\"Test adding a schedule to a user\"\"\"\n",
      "        self.db_module.select_data = MagicMock(return_value = ['a'])\n",
      "        self.db_module.update_data = MagicMock()\n",
      "        self.user_management.user_exists = MagicMock(return_value=True)\n",
      "        self.user_management.users = {\"test_id\": User(\"test_id\", \"test_user\",\n",
      "                                                        \"test_email\", [],\n",
      "                                                        \"test_password\")}\n",
      ">       self.user_management.add_schedule_to_user(\"test_id\", \"test_schedule\",\n",
      "                                                  \"write\")\n",
      "\n",
      "tests\\test_users\\test_user_management_module.py:210: \n",
      "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n",
      "src\\user\\user_management.py:208: in add_schedule_to_user\n",
      "    user = self.get_user(user_id)\n",
      "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n",
      "\n",
      "self = <src.user.user_management.UserManagement object at 0x0000021DE1F29160>\n",
      "user_id = 'test_id'\n",
      "\n",
      "    def get_user(self, user_id: str) -> User:\n",
      "        \"\"\"\n",
      "        Get a user\n",
      "    \n",
      "        Args:\n",
      "            user_id: User ID\n",
      "    \n",
      "        Returns:\n",
      "            The user if it exists, None otherwise\n",
      "        \"\"\"\n",
      "        data = self.db_module.select_data('users', {\"_id\": user_id})\n",
      ">       print(data[0])\n",
      "E       TypeError: 'Mock' object is not subscriptable\n",
      "\n",
      "src\\user\\user_management.py:164: TypeError\n",
      "=========================== short test summary info ===========================\n",
      "FAILED tests/test_users/test_user_management_module.py::TestUserManagementModule::test_add_schedule_to_user\n",
      "======================== 1 failed, 11 passed in 0.88s =========================\n"
     ]
    }
   ],
   "source": [
    "!coverage run -m pytest tests/test_users/test_user_management_module.py"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
