{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Para executar os testes, basta executar o comando abaixo:\n",
    "\n",
    "```bash\n",
    "python -m pytest\n",
    "```\n",
    "\n",
    "Alternativamente, rode a celula abaixo"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1008,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pymongo in c:\\users\\rodrigopintucci\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\\localcache\\local-packages\\python39\\site-packages (from -r requirements.txt (line 1)) (4.6.1)\n",
      "Requirement already satisfied: customtkinter in c:\\users\\rodrigopintucci\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\\localcache\\local-packages\\python39\\site-packages (from -r requirements.txt (line 2)) (5.2.1)\n",
      "Requirement already satisfied: pytest in c:\\users\\rodrigopintucci\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\\localcache\\local-packages\\python39\\site-packages (from -r requirements.txt (line 3)) (7.4.3)\n",
      "Requirement already satisfied: bcrypt in c:\\users\\rodrigopintucci\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\\localcache\\local-packages\\python39\\site-packages (from -r requirements.txt (line 4)) (4.1.1)\n",
      "Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in c:\\users\\rodrigopintucci\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\\localcache\\local-packages\\python39\\site-packages (from pymongo->-r requirements.txt (line 1)) (2.4.2)\n",
      "Requirement already satisfied: darkdetect in c:\\users\\rodrigopintucci\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\\localcache\\local-packages\\python39\\site-packages (from customtkinter->-r requirements.txt (line 2)) (0.8.0)\n",
      "Requirement already satisfied: iniconfig in c:\\users\\rodrigopintucci\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\\localcache\\local-packages\\python39\\site-packages (from pytest->-r requirements.txt (line 3)) (2.0.0)\n",
      "Requirement already satisfied: tomli>=1.0.0 in c:\\users\\rodrigopintucci\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\\localcache\\local-packages\\python39\\site-packages (from pytest->-r requirements.txt (line 3)) (2.0.1)\n",
      "Requirement already satisfied: exceptiongroup>=1.0.0rc8 in c:\\users\\rodrigopintucci\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\\localcache\\local-packages\\python39\\site-packages (from pytest->-r requirements.txt (line 3)) (1.2.0)\n",
      "Requirement already satisfied: pluggy<2.0,>=0.12 in c:\\users\\rodrigopintucci\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\\localcache\\local-packages\\python39\\site-packages (from pytest->-r requirements.txt (line 3)) (1.3.0)\n",
      "Requirement already satisfied: colorama in c:\\users\\rodrigopintucci\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\\localcache\\local-packages\\python39\\site-packages (from pytest->-r requirements.txt (line 3)) (0.3.9)\n",
      "Requirement already satisfied: packaging in c:\\users\\rodrigopintucci\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\\localcache\\local-packages\\python39\\site-packages (from pytest->-r requirements.txt (line 3)) (21.3)\n",
      "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\\users\\rodrigopintucci\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\\localcache\\local-packages\\python39\\site-packages (from packaging->pytest->-r requirements.txt (line 3)) (3.0.9)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "[notice] A new release of pip available: 22.3.1 -> 23.3.1\n",
      "[notice] To update, run: C:\\Users\\RodrigoPintucci\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\python.exe -m pip install --upgrade pip\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "============================= test session starts =============================\n",
      "platform win32 -- Python 3.9.13, pytest-7.4.3, pluggy-1.3.0\n",
      "rootdir: c:\\Users\\RodrigoPintucci\\Documents\\EngenhariaSoftware\\Engenharia_Software\n",
      "collected 213 items\n",
      "\n",
      "tests\\test_auth\\test_authentication_module.py .....                      [  2%]\n",
      "tests\\test_events\\test_element_event.py ...FFFF.....................     [ 15%]\n",
      "tests\\test_events\\test_element_factory.py ....                           [ 17%]\n",
      "tests\\test_events\\test_element_management.py ...................         [ 26%]\n",
      "tests\\test_events\\test_element_reminder.py ..........................    [ 38%]\n",
      "tests\\test_events\\test_element_task.py .............................     [ 52%]\n",
      "tests\\test_mongomodule\\test_mongo_module.py ......                       [ 54%]\n",
      "tests\\test_schedule\\test_schedule_management.py ........................ [ 66%]\n",
      ".....                                                                    [ 68%]\n",
      "tests\\test_schedule\\test_schedule_model.py ............................. [ 82%]\n",
      "                                                                         [ 82%]\n",
      "tests\\test_schedule\\test_schedule_observer.py .......                    [ 85%]\n",
      "tests\\test_users\\test_user_management_module.py FFFFF.F..F..             [ 91%]\n",
      "tests\\test_users\\test_user_model.py ...................                  [100%]\n",
      "\n",
      "================================== FAILURES ===================================\n",
      "_______________________ TestEventElement.test_get_users _______________________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_events.test_element_event.TestEventElement testMethod=test_get_users>\n",
      "\n",
      "    def test_get_users(self):\n",
      "        \"\"\"\n",
      "        Test if the users returned match the ones that were set in the\n",
      "        constructor\n",
      "        \"\"\"\n",
      "        # Set up the mock objects and functions\n",
      "        get_schedule_mock, _, _ = self.get_mock_schedule()\n",
      "        get_user_mock, user_1, user_2, user_3, user_4 = self.get_mock_user()\n",
      "    \n",
      "        with unittest.mock.patch.object(\n",
      "            ScheduleManagement, \"get_schedule\", side_effect=get_schedule_mock\n",
      "        ):\n",
      "            with unittest.mock.patch.object(\n",
      "                UserManagement, \"get_user\", side_effect=get_user_mock\n",
      "            ):\n",
      "                users = self.event.get_users([\"schedule_1\", \"schedule_2\"])\n",
      "                self.assertEqual(len(users), 4)\n",
      "                for user in users:\n",
      ">                   self.assertIn(user, [user_1, user_2, user_3, user_4])\n",
      "E                   AssertionError: <MagicMock id='1577769268224'> not found in [<MagicMock spec='User' id='1577769455232'>, <MagicMock spec='User' id='1577769447040'>, <MagicMock spec='User' id='1577769454608'>, <MagicMock spec='User' id='1577769471904'>]\n",
      "\n",
      "tests\\test_events\\test_element_event.py:94: AssertionError\n",
      "__________________ TestEventElement.test_get_users_nonfilter __________________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_events.test_element_event.TestEventElement testMethod=test_get_users_nonfilter>\n",
      "\n",
      "    def test_get_users_nonfilter(self):\n",
      "        \"\"\"Test get_users when no filter of schedules are not specified.\n",
      "        Default to all schedules.\n",
      "        #\"\"\"\n",
      "        # Set up the mock objects and functions\n",
      "        get_schedule_mock, _, _ = self.get_mock_schedule()\n",
      "        get_user_mock, user_1, user_2, user_3, user_4 = self.get_mock_user()\n",
      "    \n",
      "        with unittest.mock.patch.object(\n",
      "            ScheduleManagement, \"get_schedule\", side_effect=get_schedule_mock\n",
      "        ):\n",
      "            with unittest.mock.patch.object(\n",
      "                UserManagement, \"get_user\", side_effect=get_user_mock\n",
      "            ):\n",
      "                users = self.event.get_users()\n",
      "                self.assertEqual(len(users), 4)\n",
      "                for user in users:\n",
      ">                   self.assertIn(user, [user_1, user_2, user_3, user_4])\n",
      "E                   AssertionError: <MagicMock id='1577769268224'> not found in [<MagicMock spec='User' id='1577769393504'>, <MagicMock spec='User' id='1577769452400'>, <MagicMock spec='User' id='1577769593584'>, <MagicMock spec='User' id='1577769452688'>]\n",
      "\n",
      "tests\\test_events\\test_element_event.py:113: AssertionError\n",
      "_______________ TestEventElement.test_get_users_nonrepeat_users _______________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_events.test_element_event.TestEventElement testMethod=test_get_users_nonrepeat_users>\n",
      "\n",
      "    def test_get_users_nonrepeat_users(self):\n",
      "        \"\"\"Test if the users returned are unique\"\"\"\n",
      "        # Set up the mock objects\n",
      "        get_schedule_mock, _, _ = self.get_mock_schedule(\n",
      "            repeat_user=True\n",
      "        )\n",
      "        get_user_mock, user_1, user_2, _, _ = self.get_mock_user()\n",
      "    \n",
      "        with unittest.mock.patch.object(\n",
      "            ScheduleManagement, \"get_schedule\", side_effect=get_schedule_mock\n",
      "        ):\n",
      "            with unittest.mock.patch.object(\n",
      "                UserManagement, \"get_user\", side_effect=get_user_mock\n",
      "            ):\n",
      "                users = self.event.get_users([\"schedule_1\", \"schedule_2\"])\n",
      "                self.assertEqual(len(users), 2)\n",
      "                for user in users:\n",
      ">                   self.assertIn(user, [user_1, user_2])\n",
      "E                   AssertionError: <MagicMock id='1577769268224'> not found in [<MagicMock spec='User' id='1577770289472'>, <MagicMock spec='User' id='1577770534272'>]\n",
      "\n",
      "tests\\test_events\\test_element_event.py:152: AssertionError\n",
      "__________ TestEventElement.test_get_users_with_filter_by_schedules ___________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_events.test_element_event.TestEventElement testMethod=test_get_users_with_filter_by_schedules>\n",
      "\n",
      "    def test_get_users_with_filter_by_schedules(self):\n",
      "        \"\"\"\n",
      "        Test if the users returned match the ones that were set in the\n",
      "        constructor and if they belong to the specified schedules\n",
      "        \"\"\"\n",
      "        # Set up the mock objects\n",
      "        get_schedule_mock, _, _ = self.get_mock_schedule()\n",
      "        get_user_mock, user_1, user_2, user_3, user_4 = self.get_mock_user()\n",
      "    \n",
      "        with unittest.mock.patch.object(\n",
      "            ScheduleManagement, \"get_schedule\", side_effect=get_schedule_mock\n",
      "        ):\n",
      "            with unittest.mock.patch.object(\n",
      "                UserManagement, \"get_user\", side_effect=get_user_mock\n",
      "            ):\n",
      "                users = self.event.get_users([\"schedule_1\"])\n",
      "                self.assertEqual(len(users), 2)\n",
      "                for user in users:\n",
      ">                   self.assertIn(user, [user_1, user_2, user_3, user_4])\n",
      "E                   AssertionError: <MagicMock id='1577769268224'> not found in [<MagicMock spec='User' id='1577770536576'>, <MagicMock spec='User' id='1577770328320'>, <MagicMock spec='User' id='1577770536864'>, <MagicMock spec='User' id='1577770522848'>]\n",
      "\n",
      "tests\\test_events\\test_element_event.py:133: AssertionError\n",
      "_______ TestUserManagementModule.test_add_schedule_to_nonexistant_user ________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_users.test_user_management_module.TestUserManagementModule testMethod=test_add_schedule_to_nonexistant_user>\n",
      "\n",
      "    def test_add_schedule_to_nonexistant_user(self):\n",
      "        \"\"\"Test adding a schedule to a nonexistent user\"\"\"\n",
      "        self.db_module.select_data = MagicMock(return_value = [])\n",
      "        with self.assertRaises(NonExistentIDError) as context:\n",
      ">           self.user_management.add_schedule_to_user(\"id2\", \"test_schedule\")\n",
      "E           TypeError: add_schedule_to_user() missing 1 required positional argument: 'permission'\n",
      "\n",
      "tests\\test_users\\test_user_management_module.py:157: TypeError\n",
      "_____________ TestUserManagementModule.test_add_schedule_to_user ______________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_users.test_user_management_module.TestUserManagementModule testMethod=test_add_schedule_to_user>\n",
      "\n",
      "    def test_add_schedule_to_user(self):\n",
      "        \"\"\"Test adding a schedule to a user\"\"\"\n",
      "        self.db_module.select_data = MagicMock(return_value = ['a'])\n",
      "        self.db_module.update_data = MagicMock()\n",
      "        self.user_management.users = {\"test_id\": User(\"test_id\", \"test_user\",\n",
      "                                                        \"test_email\", [],\n",
      "                                                        \"test_password\")}\n",
      ">       self.user_management.add_schedule_to_user(\"test_id\", \"test_schedule\")\n",
      "E       TypeError: add_schedule_to_user() missing 1 required positional argument: 'permission'\n",
      "\n",
      "tests\\test_users\\test_user_management_module.py:147: TypeError\n",
      "_____________ TestUserManagementModule.test_create_blank_username _____________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_users.test_user_management_module.TestUserManagementModule testMethod=test_create_blank_username>\n",
      "\n",
      "    def test_create_blank_username(self):\n",
      "        \"\"\"Test creating a user with a blank username\"\"\"\n",
      "        with self.assertRaises(UsernameCantBeBlank) as context:\n",
      ">           self.user_management.create_user(username=\"\",\n",
      "                            email=\"test_email\", password=\"test_password\", id=\"1\")\n",
      "E           TypeError: create_user() got an unexpected keyword argument 'id'\n",
      "\n",
      "tests\\test_users\\test_user_management_module.py:85: TypeError\n",
      "_____________ TestUserManagementModule.test_create_existing_user ______________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_users.test_user_management_module.TestUserManagementModule testMethod=test_create_existing_user>\n",
      "\n",
      "    def test_create_existing_user(self):\n",
      "        \"\"\"Test creating a user that already exists\"\"\"\n",
      "        self.db_module.select_data = MagicMock(return_value =\n",
      "                                    [{\"username\": \"test_user\",\n",
      "                                      \"email\": \"test_email\",\n",
      "                                      \"hashed_password\": \"test_hashed_password\"}])\n",
      "    \n",
      "        with self.assertRaises(DuplicatedIDError) as context:\n",
      ">           self.user_management.create_user(username=\"test_user\",\n",
      "                            email=\"test_email\", password=\"test_password\", id=\"1\")\n",
      "E           TypeError: create_user() got an unexpected keyword argument 'id'\n",
      "\n",
      "tests\\test_users\\test_user_management_module.py:77: TypeError\n",
      "______________ TestUserManagementModule.test_create_user_success ______________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_users.test_user_management_module.TestUserManagementModule testMethod=test_create_user_success>\n",
      "\n",
      "    def test_create_user_success(self):\n",
      "        \"\"\"Test creating a new user successfully\"\"\"\n",
      "        self.db_module.insert_data = MagicMock(return_value =\n",
      "                                    [{\"username\": \"test_user\",\n",
      "                                      \"email\": \"test_email\",\n",
      "                                      \"hashed_password\": \"test_hashed_password\"}])\n",
      "        self.db_module.select_data = MagicMock(return_value = [])\n",
      "        result = self.user_management.create_user(username=\"test_user\",\n",
      "                        email=\"test_email\", password=\"test_password\", user_id=\"1\")\n",
      "        self.assertEqual(result.username, \"test_user\")\n",
      "        self.assertEqual(result.email, \"test_email\")\n",
      "        self.assertTrue(bcrypt.checkpw(\"test_password\".encode('utf-8'),\n",
      ">                                      result.hashed_password.encode('utf-8')),\n",
      "                        result.hashed_password)\n",
      "E       AttributeError: 'User' object has no attribute 'hashed_password'\n",
      "\n",
      "tests\\test_users\\test_user_management_module.py:44: AttributeError\n",
      "__________________ TestUserManagementModule.test_delete_user __________________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_users.test_user_management_module.TestUserManagementModule testMethod=test_delete_user>\n",
      "\n",
      "    def test_delete_user(self):\n",
      "        \"\"\"Test deleting a user\"\"\"\n",
      "        self.db_module.select_data = MagicMock(return_value = ['a'])\n",
      "        self.db_module.delete_data = MagicMock()\n",
      ">       self.user_management.delete_user(\"test_user\")\n",
      "\n",
      "tests\\test_users\\test_user_management_module.py:100: \n",
      "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n",
      "src\\user\\user_management.py:111: in delete_user\n",
      "    user = self.get_user(user_id)\n",
      "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n",
      "\n",
      "self = <src.user.user_management.UserManagement object at 0x0000016F5A7FB520>\n",
      "user_id = 'test_user'\n",
      "\n",
      "    def get_user(self, user_id: str) -> User:\n",
      "        \"\"\"\n",
      "        Get a user\n",
      "    \n",
      "        Args:\n",
      "            user_id: User ID\n",
      "    \n",
      "        Returns:\n",
      "            The user if it exists, None otherwise\n",
      "        \"\"\"\n",
      "        data = self.db_module.select_data('users', {\"_id\": user_id})\n",
      "        print(data[0])\n",
      ">       user = User(**data[0])\n",
      "E       TypeError: src.user.user_model.User() argument after ** must be a mapping, not str\n",
      "\n",
      "src\\user\\user_management.py:165: TypeError\n",
      "---------------------------- Captured stdout call -----------------------------\n",
      "a\n",
      "__________________ TestUserManagementModule.test_update_user __________________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_users.test_user_management_module.TestUserManagementModule testMethod=test_update_user>\n",
      "\n",
      "    def test_update_user(self):\n",
      "        \"\"\"Test updating a user\"\"\"\n",
      "        self.db_module.select_data = MagicMock(return_value = ['a'])\n",
      "        self.db_module.update_data = MagicMock()\n",
      "        self.user_management.users = {\"test_user\": User(\"test_user\", \"test_email\",\n",
      "                                                        \"test_password\", \"test_id\")}\n",
      "        self.user_management.update_user(\"test_user\")\n",
      ">       self.db_module.update_data.assert_called_once_with(\"users\", {\"_id\": \"test_user\"},\n",
      "                                {'id': 'test_user', 'username': 'test_email',\n",
      "                                'email': 'test_password', 'schedules': 'test_id',\n",
      "                                'password': None, 'user_preferences': {}})\n",
      "\n",
      "tests\\test_users\\test_user_management_module.py:128: \n",
      "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n",
      "C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\\lib\\unittest\\mock.py:919: in assert_called_once_with\n",
      "    return self.assert_called_with(*args, **kwargs)\n",
      "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n",
      "\n",
      "self = <MagicMock name='mock.update_data' id='1577770152384'>\n",
      "args = ('users', {'_id': 'test_user'}, {'email': 'test_password', 'id': 'test_user', 'password': None, 'schedules': 'test_id', ...})\n",
      "kwargs = {}\n",
      "expected = call('users', {'_id': 'test_user'}, {'id': 'test_user', 'username': 'test_email', 'email': 'test_password', 'schedules': 'test_id', 'password': None, 'user_preferences': {}})\n",
      "actual = call('users', {'_id': 'test_user'}, {'_id': 'test_user', 'username': 'test_email', 'email': 'test_password', 'schedules': 'test_id', 'hashed_password': None, 'user_preferences': {}})\n",
      "_error_message = <function NonCallableMock.assert_called_with.<locals>._error_message at 0x0000016F5A6C8D30>\n",
      "cause = None\n",
      "\n",
      "    def assert_called_with(self, /, *args, **kwargs):\n",
      "        \"\"\"assert that the last call was made with the specified arguments.\n",
      "    \n",
      "        Raises an AssertionError if the args and keyword args passed in are\n",
      "        different to the last call to the mock.\"\"\"\n",
      "        if self.call_args is None:\n",
      "            expected = self._format_mock_call_signature(args, kwargs)\n",
      "            actual = 'not called.'\n",
      "            error_message = ('expected call not found.\\nExpected: %s\\nActual: %s'\n",
      "                    % (expected, actual))\n",
      "            raise AssertionError(error_message)\n",
      "    \n",
      "        def _error_message():\n",
      "            msg = self._format_mock_failure_message(args, kwargs)\n",
      "            return msg\n",
      "        expected = self._call_matcher(_Call((args, kwargs), two=True))\n",
      "        actual = self._call_matcher(self.call_args)\n",
      "        if actual != expected:\n",
      "            cause = expected if isinstance(expected, Exception) else None\n",
      ">           raise AssertionError(_error_message()) from cause\n",
      "E           AssertionError: expected call not found.\n",
      "E           Expected: update_data('users', {'_id': 'test_user'}, {'id': 'test_user', 'username': 'test_email', 'email': 'test_password', 'schedules': 'test_id', 'password': None, 'user_preferences': {}})\n",
      "E           Actual: update_data('users', {'_id': 'test_user'}, {'_id': 'test_user', 'username': 'test_email', 'email': 'test_password', 'schedules': 'test_id', 'hashed_password': None, 'user_preferences': {}})\n",
      "\n",
      "C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\\lib\\unittest\\mock.py:907: AssertionError\n",
      "=========================== short test summary info ===========================\n",
      "FAILED tests/test_events/test_element_event.py::TestEventElement::test_get_users\n",
      "FAILED tests/test_events/test_element_event.py::TestEventElement::test_get_users_nonfilter\n",
      "FAILED tests/test_events/test_element_event.py::TestEventElement::test_get_users_nonrepeat_users\n",
      "FAILED tests/test_events/test_element_event.py::TestEventElement::test_get_users_with_filter_by_schedules\n",
      "FAILED tests/test_users/test_user_management_module.py::TestUserManagementModule::test_add_schedule_to_nonexistant_user\n",
      "FAILED tests/test_users/test_user_management_module.py::TestUserManagementModule::test_add_schedule_to_user\n",
      "FAILED tests/test_users/test_user_management_module.py::TestUserManagementModule::test_create_blank_username\n",
      "FAILED tests/test_users/test_user_management_module.py::TestUserManagementModule::test_create_existing_user\n",
      "FAILED tests/test_users/test_user_management_module.py::TestUserManagementModule::test_create_user_success\n",
      "FAILED tests/test_users/test_user_management_module.py::TestUserManagementModule::test_delete_user\n",
      "FAILED tests/test_users/test_user_management_module.py::TestUserManagementModule::test_update_user\n",
      "======================= 11 failed, 202 passed in 1.66s ========================\n"
     ]
    }
   ],
   "source": [
    "!pip install -r requirements.txt\n",
    "!python -m pytest"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1009,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: coverage in c:\\users\\rodrigopintucci\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\\localcache\\local-packages\\python39\\site-packages (7.3.2)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "[notice] A new release of pip available: 22.3.1 -> 23.3.1\n",
      "[notice] To update, run: C:\\Users\\RodrigoPintucci\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\python.exe -m pip install --upgrade pip\n"
     ]
    }
   ],
   "source": [
    "!pip install coverage"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1010,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "============================= test session starts =============================\n",
      "platform win32 -- Python 3.9.13, pytest-7.4.3, pluggy-1.3.0\n",
      "rootdir: c:\\Users\\RodrigoPintucci\\Documents\\EngenhariaSoftware\\Engenharia_Software\n",
      "collected 213 items\n",
      "\n",
      "tests\\test_auth\\test_authentication_module.py .....                      [  2%]\n",
      "tests\\test_events\\test_element_event.py ...FFFF.....................     [ 15%]\n",
      "tests\\test_events\\test_element_factory.py ....                           [ 17%]\n",
      "tests\\test_events\\test_element_management.py ...................         [ 26%]\n",
      "tests\\test_events\\test_element_reminder.py ..........................    [ 38%]\n",
      "tests\\test_events\\test_element_task.py .............................     [ 52%]\n",
      "tests\\test_mongomodule\\test_mongo_module.py ......                       [ 54%]\n",
      "tests\\test_schedule\\test_schedule_management.py ........................ [ 66%]\n",
      ".....                                                                    [ 68%]\n",
      "tests\\test_schedule\\test_schedule_model.py ............................. [ 82%]\n",
      "                                                                         [ 82%]\n",
      "tests\\test_schedule\\test_schedule_observer.py .......                    [ 85%]\n",
      "tests\\test_users\\test_user_management_module.py FFFFF.F..F..             [ 91%]\n",
      "tests\\test_users\\test_user_model.py ...................                  [100%]\n",
      "\n",
      "================================== FAILURES ===================================\n",
      "_______________________ TestEventElement.test_get_users _______________________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_events.test_element_event.TestEventElement testMethod=test_get_users>\n",
      "\n",
      "    def test_get_users(self):\n",
      "        \"\"\"\n",
      "        Test if the users returned match the ones that were set in the\n",
      "        constructor\n",
      "        \"\"\"\n",
      "        # Set up the mock objects and functions\n",
      "        get_schedule_mock, _, _ = self.get_mock_schedule()\n",
      "        get_user_mock, user_1, user_2, user_3, user_4 = self.get_mock_user()\n",
      "    \n",
      "        with unittest.mock.patch.object(\n",
      "            ScheduleManagement, \"get_schedule\", side_effect=get_schedule_mock\n",
      "        ):\n",
      "            with unittest.mock.patch.object(\n",
      "                UserManagement, \"get_user\", side_effect=get_user_mock\n",
      "            ):\n",
      "                users = self.event.get_users([\"schedule_1\", \"schedule_2\"])\n",
      "                self.assertEqual(len(users), 4)\n",
      "                for user in users:\n",
      ">                   self.assertIn(user, [user_1, user_2, user_3, user_4])\n",
      "E                   AssertionError: <MagicMock id='2124955573936'> not found in [<MagicMock spec='User' id='2124955877728'>, <MagicMock spec='User' id='2124955893872'>, <MagicMock spec='User' id='2124955877824'>, <MagicMock spec='User' id='2124955862496'>]\n",
      "\n",
      "tests\\test_events\\test_element_event.py:94: AssertionError\n",
      "__________________ TestEventElement.test_get_users_nonfilter __________________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_events.test_element_event.TestEventElement testMethod=test_get_users_nonfilter>\n",
      "\n",
      "    def test_get_users_nonfilter(self):\n",
      "        \"\"\"Test get_users when no filter of schedules are not specified.\n",
      "        Default to all schedules.\n",
      "        #\"\"\"\n",
      "        # Set up the mock objects and functions\n",
      "        get_schedule_mock, _, _ = self.get_mock_schedule()\n",
      "        get_user_mock, user_1, user_2, user_3, user_4 = self.get_mock_user()\n",
      "    \n",
      "        with unittest.mock.patch.object(\n",
      "            ScheduleManagement, \"get_schedule\", side_effect=get_schedule_mock\n",
      "        ):\n",
      "            with unittest.mock.patch.object(\n",
      "                UserManagement, \"get_user\", side_effect=get_user_mock\n",
      "            ):\n",
      "                users = self.event.get_users()\n",
      "                self.assertEqual(len(users), 4)\n",
      "                for user in users:\n",
      ">                   self.assertIn(user, [user_1, user_2, user_3, user_4])\n",
      "E                   AssertionError: <MagicMock id='2124955573936'> not found in [<MagicMock spec='User' id='2124955880896'>, <MagicMock spec='User' id='2124955928896'>, <MagicMock spec='User' id='2124955834736'>, <MagicMock spec='User' id='2124955926928'>]\n",
      "\n",
      "tests\\test_events\\test_element_event.py:113: AssertionError\n",
      "_______________ TestEventElement.test_get_users_nonrepeat_users _______________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_events.test_element_event.TestEventElement testMethod=test_get_users_nonrepeat_users>\n",
      "\n",
      "    def test_get_users_nonrepeat_users(self):\n",
      "        \"\"\"Test if the users returned are unique\"\"\"\n",
      "        # Set up the mock objects\n",
      "        get_schedule_mock, _, _ = self.get_mock_schedule(\n",
      "            repeat_user=True\n",
      "        )\n",
      "        get_user_mock, user_1, user_2, _, _ = self.get_mock_user()\n",
      "    \n",
      "        with unittest.mock.patch.object(\n",
      "            ScheduleManagement, \"get_schedule\", side_effect=get_schedule_mock\n",
      "        ):\n",
      "            with unittest.mock.patch.object(\n",
      "                UserManagement, \"get_user\", side_effect=get_user_mock\n",
      "            ):\n",
      "                users = self.event.get_users([\"schedule_1\", \"schedule_2\"])\n",
      "                self.assertEqual(len(users), 2)\n",
      "                for user in users:\n",
      ">                   self.assertIn(user, [user_1, user_2])\n",
      "E                   AssertionError: <MagicMock id='2124955573936'> not found in [<MagicMock spec='User' id='2124955535920'>, <MagicMock spec='User' id='2124955483776'>]\n",
      "\n",
      "tests\\test_events\\test_element_event.py:152: AssertionError\n",
      "__________ TestEventElement.test_get_users_with_filter_by_schedules ___________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_events.test_element_event.TestEventElement testMethod=test_get_users_with_filter_by_schedules>\n",
      "\n",
      "    def test_get_users_with_filter_by_schedules(self):\n",
      "        \"\"\"\n",
      "        Test if the users returned match the ones that were set in the\n",
      "        constructor and if they belong to the specified schedules\n",
      "        \"\"\"\n",
      "        # Set up the mock objects\n",
      "        get_schedule_mock, _, _ = self.get_mock_schedule()\n",
      "        get_user_mock, user_1, user_2, user_3, user_4 = self.get_mock_user()\n",
      "    \n",
      "        with unittest.mock.patch.object(\n",
      "            ScheduleManagement, \"get_schedule\", side_effect=get_schedule_mock\n",
      "        ):\n",
      "            with unittest.mock.patch.object(\n",
      "                UserManagement, \"get_user\", side_effect=get_user_mock\n",
      "            ):\n",
      "                users = self.event.get_users([\"schedule_1\"])\n",
      "                self.assertEqual(len(users), 2)\n",
      "                for user in users:\n",
      ">                   self.assertIn(user, [user_1, user_2, user_3, user_4])\n",
      "E                   AssertionError: <MagicMock id='2124955573936'> not found in [<MagicMock spec='User' id='2124955851648'>, <MagicMock spec='User' id='2124955836320'>, <MagicMock spec='User' id='2124955851120'>, <MagicMock spec='User' id='2124955854208'>]\n",
      "\n",
      "tests\\test_events\\test_element_event.py:133: AssertionError\n",
      "_______ TestUserManagementModule.test_add_schedule_to_nonexistant_user ________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_users.test_user_management_module.TestUserManagementModule testMethod=test_add_schedule_to_nonexistant_user>\n",
      "\n",
      "    def test_add_schedule_to_nonexistant_user(self):\n",
      "        \"\"\"Test adding a schedule to a nonexistent user\"\"\"\n",
      "        self.db_module.select_data = MagicMock(return_value = [])\n",
      "        with self.assertRaises(NonExistentIDError) as context:\n",
      ">           self.user_management.add_schedule_to_user(\"id2\", \"test_schedule\")\n",
      "E           TypeError: add_schedule_to_user() missing 1 required positional argument: 'permission'\n",
      "\n",
      "tests\\test_users\\test_user_management_module.py:157: TypeError\n",
      "_____________ TestUserManagementModule.test_add_schedule_to_user ______________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_users.test_user_management_module.TestUserManagementModule testMethod=test_add_schedule_to_user>\n",
      "\n",
      "    def test_add_schedule_to_user(self):\n",
      "        \"\"\"Test adding a schedule to a user\"\"\"\n",
      "        self.db_module.select_data = MagicMock(return_value = ['a'])\n",
      "        self.db_module.update_data = MagicMock()\n",
      "        self.user_management.users = {\"test_id\": User(\"test_id\", \"test_user\",\n",
      "                                                        \"test_email\", [],\n",
      "                                                        \"test_password\")}\n",
      ">       self.user_management.add_schedule_to_user(\"test_id\", \"test_schedule\")\n",
      "E       TypeError: add_schedule_to_user() missing 1 required positional argument: 'permission'\n",
      "\n",
      "tests\\test_users\\test_user_management_module.py:147: TypeError\n",
      "_____________ TestUserManagementModule.test_create_blank_username _____________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_users.test_user_management_module.TestUserManagementModule testMethod=test_create_blank_username>\n",
      "\n",
      "    def test_create_blank_username(self):\n",
      "        \"\"\"Test creating a user with a blank username\"\"\"\n",
      "        with self.assertRaises(UsernameCantBeBlank) as context:\n",
      ">           self.user_management.create_user(username=\"\",\n",
      "                            email=\"test_email\", password=\"test_password\", id=\"1\")\n",
      "E           TypeError: create_user() got an unexpected keyword argument 'id'\n",
      "\n",
      "tests\\test_users\\test_user_management_module.py:85: TypeError\n",
      "_____________ TestUserManagementModule.test_create_existing_user ______________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_users.test_user_management_module.TestUserManagementModule testMethod=test_create_existing_user>\n",
      "\n",
      "    def test_create_existing_user(self):\n",
      "        \"\"\"Test creating a user that already exists\"\"\"\n",
      "        self.db_module.select_data = MagicMock(return_value =\n",
      "                                    [{\"username\": \"test_user\",\n",
      "                                      \"email\": \"test_email\",\n",
      "                                      \"hashed_password\": \"test_hashed_password\"}])\n",
      "    \n",
      "        with self.assertRaises(DuplicatedIDError) as context:\n",
      ">           self.user_management.create_user(username=\"test_user\",\n",
      "                            email=\"test_email\", password=\"test_password\", id=\"1\")\n",
      "E           TypeError: create_user() got an unexpected keyword argument 'id'\n",
      "\n",
      "tests\\test_users\\test_user_management_module.py:77: TypeError\n",
      "______________ TestUserManagementModule.test_create_user_success ______________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_users.test_user_management_module.TestUserManagementModule testMethod=test_create_user_success>\n",
      "\n",
      "    def test_create_user_success(self):\n",
      "        \"\"\"Test creating a new user successfully\"\"\"\n",
      "        self.db_module.insert_data = MagicMock(return_value =\n",
      "                                    [{\"username\": \"test_user\",\n",
      "                                      \"email\": \"test_email\",\n",
      "                                      \"hashed_password\": \"test_hashed_password\"}])\n",
      "        self.db_module.select_data = MagicMock(return_value = [])\n",
      "        result = self.user_management.create_user(username=\"test_user\",\n",
      "                        email=\"test_email\", password=\"test_password\", user_id=\"1\")\n",
      "        self.assertEqual(result.username, \"test_user\")\n",
      "        self.assertEqual(result.email, \"test_email\")\n",
      "        self.assertTrue(bcrypt.checkpw(\"test_password\".encode('utf-8'),\n",
      ">                                      result.hashed_password.encode('utf-8')),\n",
      "                        result.hashed_password)\n",
      "E       AttributeError: 'User' object has no attribute 'hashed_password'\n",
      "\n",
      "tests\\test_users\\test_user_management_module.py:44: AttributeError\n",
      "__________________ TestUserManagementModule.test_delete_user __________________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_users.test_user_management_module.TestUserManagementModule testMethod=test_delete_user>\n",
      "\n",
      "    def test_delete_user(self):\n",
      "        \"\"\"Test deleting a user\"\"\"\n",
      "        self.db_module.select_data = MagicMock(return_value = ['a'])\n",
      "        self.db_module.delete_data = MagicMock()\n",
      ">       self.user_management.delete_user(\"test_user\")\n",
      "\n",
      "tests\\test_users\\test_user_management_module.py:100: \n",
      "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n",
      "src\\user\\user_management.py:111: in delete_user\n",
      "    user = self.get_user(user_id)\n",
      "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n",
      "\n",
      "self = <src.user.user_management.UserManagement object at 0x000001EEC14AB7F0>\n",
      "user_id = 'test_user'\n",
      "\n",
      "    def get_user(self, user_id: str) -> User:\n",
      "        \"\"\"\n",
      "        Get a user\n",
      "    \n",
      "        Args:\n",
      "            user_id: User ID\n",
      "    \n",
      "        Returns:\n",
      "            The user if it exists, None otherwise\n",
      "        \"\"\"\n",
      "        data = self.db_module.select_data('users', {\"_id\": user_id})\n",
      "        print(data[0])\n",
      ">       user = User(**data[0])\n",
      "E       TypeError: src.user.user_model.User() argument after ** must be a mapping, not str\n",
      "\n",
      "src\\user\\user_management.py:165: TypeError\n",
      "---------------------------- Captured stdout call -----------------------------\n",
      "a\n",
      "__________________ TestUserManagementModule.test_update_user __________________\n",
      "\n",
      "self = <Engenharia_Software.tests.test_users.test_user_management_module.TestUserManagementModule testMethod=test_update_user>\n",
      "\n",
      "    def test_update_user(self):\n",
      "        \"\"\"Test updating a user\"\"\"\n",
      "        self.db_module.select_data = MagicMock(return_value = ['a'])\n",
      "        self.db_module.update_data = MagicMock()\n",
      "        self.user_management.users = {\"test_user\": User(\"test_user\", \"test_email\",\n",
      "                                                        \"test_password\", \"test_id\")}\n",
      "        self.user_management.update_user(\"test_user\")\n",
      ">       self.db_module.update_data.assert_called_once_with(\"users\", {\"_id\": \"test_user\"},\n",
      "                                {'id': 'test_user', 'username': 'test_email',\n",
      "                                'email': 'test_password', 'schedules': 'test_id',\n",
      "                                'password': None, 'user_preferences': {}})\n",
      "\n",
      "tests\\test_users\\test_user_management_module.py:128: \n",
      "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n",
      "C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\\lib\\unittest\\mock.py:919: in assert_called_once_with\n",
      "    return self.assert_called_with(*args, **kwargs)\n",
      "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n",
      "\n",
      "self = <MagicMock name='mock.update_data' id='2124958055920'>\n",
      "args = ('users', {'_id': 'test_user'}, {'email': 'test_password', 'id': 'test_user', 'password': None, 'schedules': 'test_id', ...})\n",
      "kwargs = {}\n",
      "expected = call('users', {'_id': 'test_user'}, {'id': 'test_user', 'username': 'test_email', 'email': 'test_password', 'schedules': 'test_id', 'password': None, 'user_preferences': {}})\n",
      "actual = call('users', {'_id': 'test_user'}, {'_id': 'test_user', 'username': 'test_email', 'email': 'test_password', 'schedules': 'test_id', 'hashed_password': None, 'user_preferences': {}})\n",
      "_error_message = <function NonCallableMock.assert_called_with.<locals>._error_message at 0x000001EEC141EDC0>\n",
      "cause = None\n",
      "\n",
      "    def assert_called_with(self, /, *args, **kwargs):\n",
      "        \"\"\"assert that the last call was made with the specified arguments.\n",
      "    \n",
      "        Raises an AssertionError if the args and keyword args passed in are\n",
      "        different to the last call to the mock.\"\"\"\n",
      "        if self.call_args is None:\n",
      "            expected = self._format_mock_call_signature(args, kwargs)\n",
      "            actual = 'not called.'\n",
      "            error_message = ('expected call not found.\\nExpected: %s\\nActual: %s'\n",
      "                    % (expected, actual))\n",
      "            raise AssertionError(error_message)\n",
      "    \n",
      "        def _error_message():\n",
      "            msg = self._format_mock_failure_message(args, kwargs)\n",
      "            return msg\n",
      "        expected = self._call_matcher(_Call((args, kwargs), two=True))\n",
      "        actual = self._call_matcher(self.call_args)\n",
      "        if actual != expected:\n",
      "            cause = expected if isinstance(expected, Exception) else None\n",
      ">           raise AssertionError(_error_message()) from cause\n",
      "E           AssertionError: expected call not found.\n",
      "E           Expected: update_data('users', {'_id': 'test_user'}, {'id': 'test_user', 'username': 'test_email', 'email': 'test_password', 'schedules': 'test_id', 'password': None, 'user_preferences': {}})\n",
      "E           Actual: update_data('users', {'_id': 'test_user'}, {'_id': 'test_user', 'username': 'test_email', 'email': 'test_password', 'schedules': 'test_id', 'hashed_password': None, 'user_preferences': {}})\n",
      "\n",
      "C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\\lib\\unittest\\mock.py:907: AssertionError\n",
      "=========================== short test summary info ===========================\n",
      "FAILED tests/test_events/test_element_event.py::TestEventElement::test_get_users\n",
      "FAILED tests/test_events/test_element_event.py::TestEventElement::test_get_users_nonfilter\n",
      "FAILED tests/test_events/test_element_event.py::TestEventElement::test_get_users_nonrepeat_users\n",
      "FAILED tests/test_events/test_element_event.py::TestEventElement::test_get_users_with_filter_by_schedules\n",
      "FAILED tests/test_users/test_user_management_module.py::TestUserManagementModule::test_add_schedule_to_nonexistant_user\n",
      "FAILED tests/test_users/test_user_management_module.py::TestUserManagementModule::test_add_schedule_to_user\n",
      "FAILED tests/test_users/test_user_management_module.py::TestUserManagementModule::test_create_blank_username\n",
      "FAILED tests/test_users/test_user_management_module.py::TestUserManagementModule::test_create_existing_user\n",
      "FAILED tests/test_users/test_user_management_module.py::TestUserManagementModule::test_create_user_success\n",
      "FAILED tests/test_users/test_user_management_module.py::TestUserManagementModule::test_delete_user\n",
      "FAILED tests/test_users/test_user_management_module.py::TestUserManagementModule::test_update_user\n",
      "======================= 11 failed, 202 passed in 1.90s ========================\n"
     ]
    }
   ],
   "source": [
    "!coverage run -m pytest"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1011,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The autoreload extension is already loaded. To reload it, use:\n",
      "  %reload_ext autoreload\n"
     ]
    }
   ],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1012,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Name                                          Stmts   Miss  Cover\n",
      "-----------------------------------------------------------------\n",
      "src\\auth\\authentication.py                       22      2    91%\n",
      "src\\calendar_elements\\element_factory.py         12      0   100%\n",
      "src\\calendar_elements\\element_interface.py       24      1    96%\n",
      "src\\calendar_elements\\element_management.py      83      2    98%\n",
      "src\\calendar_elements\\element_types.py          231      7    97%\n",
      "src\\database\\database_module.py                  14      0   100%\n",
      "src\\database\\mongo_module.py                     44      0   100%\n",
      "src\\database\\utils.py                            65     50    23%\n",
      "src\\observer\\observer.py                         14      1    93%\n",
      "src\\schedule\\schedule_management.py              99      1    99%\n",
      "src\\schedule\\schedule_model.py                   79      4    95%\n",
      "src\\user\\user_management.py                      84     31    63%\n",
      "src\\user\\user_model.py                          107     20    81%\n",
      "-----------------------------------------------------------------\n",
      "TOTAL                                           878    119    86%\n"
     ]
    }
   ],
   "source": [
    "# explicação do copitot:\n",
    "# Name: nome do arquivo testado\n",
    "# Stmts: número de linhas executadas\n",
    "# Miss: número de linhas não executadas\n",
    "# Cover: porcentagem de cobertura\n",
    "# Missing: linhas não executadas\n",
    "# !coverage report -m\n",
    "\n",
    "!coverage report --omit \"*__init__*,*/lib/*,tests/*\""
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Rode a célula (ou o comando) abaixo para gerar um relatório de cobertura em html dos testes:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1013,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Wrote HTML report to htmlcov\\index.html\n"
     ]
    }
   ],
   "source": [
    "!coverage html --omit \"*__init__*,*/lib/*,tests/*\"\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1014,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "============================= test session starts =============================\n",
      "platform win32 -- Python 3.9.13, pytest-7.4.3, pluggy-1.3.0\n",
      "rootdir: c:\\Users\\RodrigoPintucci\\Documents\\EngenhariaSoftware\\Engenharia_Software\n",
      "collected 28 items\n",
      "\n",
      "tests\\test_events\\test_element_event.py ............................     [100%]\n",
      "\n",
      "============================= 28 passed in 0.39s ==============================\n"
     ]
    }
   ],
   "source": [
    "# rodando um teste específico\n",
    "!coverage run -m pytest tests/test_events/test_element_event.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1015,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "============================= test session starts =============================\n",
      "platform win32 -- Python 3.9.13, pytest-7.4.3, pluggy-1.3.0\n",
      "rootdir: c:\\Users\\RodrigoPintucci\\Documents\\EngenhariaSoftware\\Engenharia_Software\n",
      "collected 7 items\n",
      "\n",
      "tests\\test_schedule\\test_schedule_observer.py .......                    [100%]\n",
      "\n",
      "============================== 7 passed in 0.32s ==============================\n"
     ]
    }
   ],
   "source": [
    "# rodando um teste específico\n",
    "!coverage run -m pytest tests/test_schedule/test_schedule_observer.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1016,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "============================= test session starts =============================\n",
      "platform win32 -- Python 3.9.13, pytest-7.4.3, pluggy-1.3.0\n",
      "rootdir: c:\\Users\\RodrigoPintucci\\Documents\\EngenhariaSoftware\\Engenharia_Software\n",
      "collected 19 items\n",
      "\n",
      "tests\\test_users\\test_user_model.py ...................                  [100%]\n",
      "\n",
      "============================= 19 passed in 0.44s ==============================\n"
     ]
    }
   ],
   "source": [
    "!coverage run -m pytest tests/test_users/test_user_model.py"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
